apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: distributed-health
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - port: 3008
      targetPort: 3008
      protocol: TCP
