apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: amzalfoumi/doctor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: doctor-service-secret
            - configMapRef:
                name: doctor-service-config
          volumeMounts:
            - name: firebase-volume
              mountPath: "/app/secrets/firebase"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-key-secret
