apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: distributed-health
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
