apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/namespace.yaml
  - api-gateway
  - notification-service
  - patient-service
  - doctor-service
  - appointment-service
  - telemedicine-service
  - payment-service
  - ai-service
