apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: distributed-health
data:
  PORT: "3001"
  AUTHENTICATION_SERVICE_URL: "http://keycloak:8080"
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "health-system"
  PATIENT_SERVICE_URL: "http://patient-service:3002"
  DOCTOR_SERVICE_URL: "http://doctor-service:3003"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:3006"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3007"
  AI_SERVICE_URL: "http://ai-service:3008"
