apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: distributed-health
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: amzalfoumi/api-gateway
  newName: amzalfoumi/api-gateway
  newTag: 97c70f5
