apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: amzalfoumi/telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3006
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: telemedicine-service-secret
                  key: MONGODB_URI
          envFrom:
            - configMapRef:
                name: telemedicine-service-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
