apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: distributed-health
spec:
  type: ClusterIP
  selector:
    app: telemedicine-service
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
