apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: amzalfoumi/patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: patient-service-secret
            - configMapRef:
                name: patient-service-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
