apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: amzalfoumi/patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_PATH
              value: "/app/secrets/firebase/service-account.json"
          envFrom:
            - secretRef:
                name: patient-service-secret
            - configMapRef:
                name: patient-service-config
          volumeMounts:
            - name: firebase-volume
              mountPath: "/app/secrets/firebase"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-key-secret
