apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: amzalfoumi/authentication-service:latest
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-config
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
