apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: distributed-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: amzalfoumi/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          envFrom:
            - secretRef:
                name: payment-service-secret
                optional: true
            - configMapRef:
                name: payment-service-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
