apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: distributed-health
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
images:
- name: amzalfoumi/payment-service
  newName: amzalfoumi/payment-service
  newTag: e2d47db
